# permissions for end users to edit dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}
  name: phonebook:editor-role
rules:
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords
  - dnsintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/status
  - dnsintegrations/status
  verbs:
  - get

