apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phonebook:controller
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords
  - dnsintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/finalizers
  - dnsintegrations/finalizers
  verbs:
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/status
  - dnsintegrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - "apps"
  resources:
    - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phonebook:providers
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phonebook:metrics
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
