# permissions for end users to view dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}
  name: phonebook:viewer-role
rules:
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords
  - dnsintegrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/status
  - dnsintegrations/status
  verbs:
  - get

