# Build the controller binary
FROM golang:1.23 AS source
ARG TARGETOS
ARG TARGETARCH
ARG PROVIDER_VERSION

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download


FROM source AS controller-builder

COPY api/ api/
COPY pkg/ pkg/
COPY internal/ internal/
COPY cmd/controller/main.go cmd/main.go

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -ldflags="-X 'github.com/pier-oliviert/phonebook/pkg/providers.ProviderVersion=${PROVIDER_VERSION}'" -a -o controller cmd/main.go


# Use distroless as minimal base image to package the controller binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot AS controller
WORKDIR /
COPY --from=controller-builder /workspace/controller .
USER 65532:65532

EXPOSE 4443

ENTRYPOINT ["/controller"]

