apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-providers
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: phonebook-providers
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: phonebook-providers
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        control-plane: phonebook-providers
        {{- include "operator.labels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /controller
        args:
        image: {{ .Values.controller.image }} 
        name: controller
        env:
          - name: PB_PROVIDER
            value: {{ required "A Provider needs to be specified: https://pier-oliviert.github.io/phonebook/providers/" .Values.provider }}
        {{- range .Values.controller.env }}
          - name: {{ .name | quote }}
            value: {{ toYaml .value }}
        {{- end }}
        {{- range ((.Values.controller).secrets).keys }}
          - name: {{ .name | quote }}
            valueFrom:
              secretKeyRef:
                name: {{ required "A secret name needs to be specified" $.Values.controller.secrets.name | quote }}
                key: {{ .key | quote }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
      serviceAccountName: phonebook-controller
      terminationGracePeriodSeconds: 10
