apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: phonebook
  name: phonebook:providers-events
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
